// Inner detector wrapper for the vision ESPHome component.
//
// This supports several ESP-DL detection model families - selected at
// build time via -DVISION_FAMILY_<N>:
//   0 = coco_detect       (YOLO11, 80 COCO classes)
//   1 = pedestrian_detect (Pico postprocessor, 1 class "person")
//   2 = hand_detect       (ESPDet postprocessor, 1 class "hand")
//   3 = human_face_detect (MSR single-stage, 1 class "face")
//   4 = coco_pose         (YOLO11 pose, 1 class "person" + 17 keypoints)
//
// Default (when VISION_FAMILY is undefined) = coco_detect.
//
// The model bytes can come from either:
//   - the build-embedded `_binary_vision_detect_espdl_start` symbol
//     (generated by vision_build.py)
//   - a runtime override set via vision_set_runtime_model_data(...)
//     before the constructor is called (e.g. jesserockz `file:` platform)

#include "vision_detect.hpp"

#ifndef VISION_FAMILY
#define VISION_FAMILY 0
#endif

#define VISION_FAMILY_COCO_DETECT               0
#define VISION_FAMILY_PEDESTRIAN_DETECT         1
#define VISION_FAMILY_HAND_DETECT               2
#define VISION_FAMILY_HUMAN_FACE_DETECT         3
#define VISION_FAMILY_COCO_POSE                 4
#define VISION_FAMILY_IMAGENET_CLS              5
#define VISION_FAMILY_HAND_GESTURE_RECOGNITION  6

// Shared storage for the runtime model override. Both detect and classify
// inner TUs use this through `extern`. Defined exactly once here.
const uint8_t *vision_runtime_model_data = nullptr;

extern "C" void vision_set_runtime_model_data(const uint8_t *data) {
    vision_runtime_model_data = data;
}

#include "esp_log.h"
#include <string.h>
#include <stdio.h>
#include <sys/stat.h>

#include "dl_detect_yolo11_postprocessor.hpp"

#if VISION_FAMILY == VISION_FAMILY_PEDESTRIAN_DETECT
#include "dl_detect_pico_postprocessor.hpp"
#elif VISION_FAMILY == VISION_FAMILY_HAND_DETECT
#include "dl_detect_espdet_postprocessor.hpp"
#elif VISION_FAMILY == VISION_FAMILY_HUMAN_FACE_DETECT
#include "dl_detect_msr_postprocessor.hpp"
#elif VISION_FAMILY == VISION_FAMILY_COCO_POSE
#include "dl_pose_yolo11_postprocessor.hpp"
#endif

#if CONFIG_YOLO11_DETECT_MODEL_IN_FLASH_RODATA
extern const uint8_t vision_detect_espdl[] asm("_binary_vision_detect_espdl_start");
static const uint8_t *flash_rodata_default = vision_detect_espdl;
#elif CONFIG_YOLO11_DETECT_MODEL_IN_FLASH_PARTITION
static const uint8_t *flash_rodata_default = nullptr;
static const char *partition_name = "vision_detect";
#endif

namespace vision_detect {

VisionDetectImpl::VisionDetectImpl(const char *model_name)
{
#if !CONFIG_YOLO11_DETECT_MODEL_IN_SDCARD
    const uint8_t *bytes = vision_runtime_model_data ? vision_runtime_model_data
                                                     : flash_rodata_default;
    if (bytes == nullptr) {
        ESP_LOGE("vision_detect", "no model data available (neither flash "
                                  "rodata nor runtime override)");
    }
    m_model = new dl::Model(
        reinterpret_cast<const char *>(bytes), model_name,
        static_cast<fbs::model_location_type_t>(CONFIG_YOLO11_DETECT_MODEL_LOCATION));
#else
    m_model = new dl::Model(
        model_name,
        static_cast<fbs::model_location_type_t>(CONFIG_YOLO11_DETECT_MODEL_LOCATION));
#endif

    // --- Per-family preprocessor + postprocessor -----------------------
#if VISION_FAMILY == VISION_FAMILY_PEDESTRIAN_DETECT
    // Pedestrian: std=1,1,1 (model expects raw uint8 values), no letterbox.
    m_image_preprocessor =
        new dl::image::ImagePreprocessor(m_model, {0, 0, 0}, {1, 1, 1});
    m_postprocessor = new dl::detect::PicoPostprocessor(
        m_model, m_image_preprocessor, 0.7, 0.5, 10,
        {{8, 8, 4, 4}, {16, 16, 8, 8}, {32, 32, 16, 16}});

#elif VISION_FAMILY == VISION_FAMILY_HAND_DETECT
    // Hand: std=255 (normalized), letterbox padded with 114 gray.
    m_image_preprocessor =
        new dl::image::ImagePreprocessor(m_model, {0, 0, 0}, {255, 255, 255});
    m_image_preprocessor->enable_letterbox({114, 114, 114});
    m_postprocessor = new dl::detect::ESPDetPostProcessor(
        m_model, m_image_preprocessor, 0.25, 0.5, 10,
        {{8, 8, 4, 4}, {16, 16, 8, 8}, {32, 32, 16, 16}});

#elif VISION_FAMILY == VISION_FAMILY_HUMAN_FACE_DETECT
    // Face MSR: std=1, rgb_swap=true (BGR input), anchor boxes per stage.
    m_image_preprocessor =
        new dl::image::ImagePreprocessor(m_model, {0, 0, 0}, {1, 1, 1}, true);
    m_postprocessor = new dl::detect::MSRPostprocessor(
        m_model, m_image_preprocessor, 0.5, 0.5, 10,
        {{8, 8, 9, 9, {{16, 16}, {32, 32}}},
         {16, 16, 9, 9, {{64, 64}, {128, 128}}}});

#elif VISION_FAMILY == VISION_FAMILY_COCO_POSE
    // Pose YOLO11: same preprocessing as coco_detect (std=255, letterbox 114),
    // postprocessor populates result_t::keypoint with 17 (x,y) COCO pose keypoints.
    m_image_preprocessor =
        new dl::image::ImagePreprocessor(m_model, {0, 0, 0}, {255, 255, 255});
    m_image_preprocessor->enable_letterbox({114, 114, 114});
    m_postprocessor = new dl::detect::yolo11posePostProcessor(
        m_model, m_image_preprocessor, 0.3, 0.3, 10,
        {{8, 8, 4, 4}, {16, 16, 8, 8}, {32, 32, 16, 16}});

#else
    // Default: coco_detect (YOLO11) - std=255, no letterbox.
    m_image_preprocessor =
        new dl::image::ImagePreprocessor(m_model, {0, 0, 0}, {255, 255, 255});
    m_postprocessor = new dl::detect::yolo11PostProcessor(
        m_model, m_image_preprocessor, 0.3, 0.3, 10,
        {{8, 8, 4, 4}, {16, 16, 8, 8}, {32, 32, 16, 16}});
#endif
}

} // namespace vision_detect

VisionDetect::VisionDetect(const char *sdcard_model_dir, model_type_t model_type)
{
    (void)sdcard_model_dir;
    switch (model_type) {
    case model_type_t::YOLO11_S8_V1:
#if CONFIG_YOLO11_DETECT_S8_V1
        m_model = new vision_detect::VisionDetectImpl("vision_model.espdl");
#else
        ESP_LOGE("vision_detect", "yolo11_detect_s8_v1 is not selected in menuconfig.");
#endif
        break;
    }
}
