// Inner detector wrapper for the yolov11 ESPHome component.
//
// Despite the file name, this supports several ESP-DL detection model
// families - selected at build time via -DVISION_FAMILY_<N>:
//   0 = coco_detect       (YOLO11, 80 COCO classes)
//   1 = pedestrian_detect (Pico postprocessor, 1 class "person")
//   2 = hand_detect       (ESPDet postprocessor, 1 class "hand")
//   3 = human_face_detect (MSR single-stage, 1 class "face")
//
// Default (when VISION_FAMILY is undefined) = coco_detect.
//
// The model bytes can come from either:
//   - the build-embedded `_binary_yolo11_detect_espdl_start` symbol
//     (generated by vision_build.py)
//   - a runtime override set via vision_set_runtime_model_data(...)
//     before the constructor is called (e.g. jesserockz `file:` platform)

#include "yolo11_detect.hpp"
#include "esp_log.h"
#include <string.h>
#include <stdio.h>
#include <sys/stat.h>

#include "dl_detect_yolo11_postprocessor.hpp"

#ifndef VISION_FAMILY
#define VISION_FAMILY 0
#endif

#define VISION_FAMILY_COCO_DETECT       0
#define VISION_FAMILY_PEDESTRIAN_DETECT 1
#define VISION_FAMILY_HAND_DETECT       2
#define VISION_FAMILY_HUMAN_FACE_DETECT 3

#if VISION_FAMILY == VISION_FAMILY_PEDESTRIAN_DETECT
#include "dl_detect_pico_postprocessor.hpp"
#elif VISION_FAMILY == VISION_FAMILY_HAND_DETECT
#include "dl_detect_espdet_postprocessor.hpp"
#elif VISION_FAMILY == VISION_FAMILY_HUMAN_FACE_DETECT
#include "dl_detect_msr_postprocessor.hpp"
#endif

#if CONFIG_YOLO11_DETECT_MODEL_IN_FLASH_RODATA
extern const uint8_t yolo11_detect_espdl[] asm("_binary_yolo11_detect_espdl_start");
static const uint8_t *flash_rodata_default = yolo11_detect_espdl;
#elif CONFIG_YOLO11_DETECT_MODEL_IN_FLASH_PARTITION
static const uint8_t *flash_rodata_default = nullptr;
static const char *partition_name = "yolo11_detect";
#endif

// Runtime override (nullable). When non-null, YOLO11Impl will load the
// model from this buffer instead of the build-embedded one.
static const uint8_t *runtime_model_data = nullptr;

extern "C" void vision_set_runtime_model_data(const uint8_t *data) {
    runtime_model_data = data;
    if (data) {
        ESP_LOGI("yolo11_detect", "runtime model override set: %p", data);
    } else {
        ESP_LOGI("yolo11_detect", "runtime model override cleared (using flash rodata)");
    }
}

namespace yolo11_detect {

YOLO11Impl::YOLO11Impl(const char *model_name)
{
#if !CONFIG_YOLO11_DETECT_MODEL_IN_SDCARD
    const uint8_t *bytes = runtime_model_data ? runtime_model_data
                                              : flash_rodata_default;
    if (bytes == nullptr) {
        ESP_LOGE("yolo11_detect", "no model data available (neither flash "
                                  "rodata nor runtime override)");
    }
    m_model = new dl::Model(
        reinterpret_cast<const char *>(bytes), model_name,
        static_cast<fbs::model_location_type_t>(CONFIG_YOLO11_DETECT_MODEL_LOCATION));
#else
    m_model = new dl::Model(
        model_name,
        static_cast<fbs::model_location_type_t>(CONFIG_YOLO11_DETECT_MODEL_LOCATION));
#endif

    // --- Per-family preprocessor + postprocessor -----------------------
#if VISION_FAMILY == VISION_FAMILY_PEDESTRIAN_DETECT
    // Pedestrian: std=1,1,1 (model expects raw uint8 values), no letterbox.
    m_image_preprocessor =
        new dl::image::ImagePreprocessor(m_model, {0, 0, 0}, {1, 1, 1});
    m_postprocessor = new dl::detect::PicoPostprocessor(
        m_model, m_image_preprocessor, 0.7, 0.5, 10,
        {{8, 8, 4, 4}, {16, 16, 8, 8}, {32, 32, 16, 16}});

#elif VISION_FAMILY == VISION_FAMILY_HAND_DETECT
    // Hand: std=255 (normalized), letterbox padded with 114 gray.
    m_image_preprocessor =
        new dl::image::ImagePreprocessor(m_model, {0, 0, 0}, {255, 255, 255});
    m_image_preprocessor->enable_letterbox({114, 114, 114});
    m_postprocessor = new dl::detect::ESPDetPostProcessor(
        m_model, m_image_preprocessor, 0.25, 0.5, 10,
        {{8, 8, 4, 4}, {16, 16, 8, 8}, {32, 32, 16, 16}});

#elif VISION_FAMILY == VISION_FAMILY_HUMAN_FACE_DETECT
    // Face MSR: std=1, rgb_swap=true (BGR input), anchor boxes per stage.
    m_image_preprocessor =
        new dl::image::ImagePreprocessor(m_model, {0, 0, 0}, {1, 1, 1}, true);
    m_postprocessor = new dl::detect::MSRPostprocessor(
        m_model, m_image_preprocessor, 0.5, 0.5, 10,
        {{8, 8, 9, 9, {{16, 16}, {32, 32}}},
         {16, 16, 9, 9, {{64, 64}, {128, 128}}}});

#else
    // Default: coco_detect (YOLO11) - std=255, no letterbox.
    m_image_preprocessor =
        new dl::image::ImagePreprocessor(m_model, {0, 0, 0}, {255, 255, 255});
    m_postprocessor = new dl::detect::yolo11PostProcessor(
        m_model, m_image_preprocessor, 0.3, 0.3, 10,
        {{8, 8, 4, 4}, {16, 16, 8, 8}, {32, 32, 16, 16}});
#endif
}

} // namespace yolo11_detect

YOLO11Detect::YOLO11Detect(const char *sdcard_model_dir, model_type_t model_type)
{
    (void)sdcard_model_dir;
    switch (model_type) {
    case model_type_t::YOLO11_S8_V1:
#if CONFIG_YOLO11_DETECT_S8_V1
        m_model = new yolo11_detect::YOLO11Impl("yolov11_model.espdl");
#else
        ESP_LOGE("yolo11_detect", "yolo11_detect_s8_v1 is not selected in menuconfig.");
#endif
        break;
    }
}
